Repository epam/edp-install, pull requests merged in 2024-05, with the labels that each got.

#200 docs: Add upgrade edp 3.8 guide
  docs/assets/operator-guide/portal-keycloak.png
  docs/operator-guide/upgrade-edp-3.8.md
  mkdocs.yml
Labels: documentation

#207 docs: Update team working flow (#206)
  docs/assets/developer-guide/merge_request.png
  docs/developer-guide/edp-workflow.md
  docs/developer-guide/local-development.md
  mkdocs.yml
Labels: documentation

#198 docs: Describe custom pipeline deployment #197
  docs/assets/operator-guide/select_trigger_template.png
  docs/operator-guide/customize_deployment.md
  mkdocs.yml
Labels: documentation

#220 chore: Add eso objects for GHCR registry (#218)
  deploy-templates/README.md
  deploy-templates/templates/external-secrets/externalsecret-kaniko.yaml
  deploy-templates/templates/external-secrets/externalsecret-regcred.yaml
  deploy-templates/values.yaml
Labels: enhancement

#224 docs: Add GitHub container registry to documentation (#223)
  docs/assets/operator-guide/container-registry-github.png
  docs/user-guide/manage-container-registries.md
Labels: documentation

#209 feat: Migrate from SSORealm to idp resources
  deploy-templates/README.md
  deploy-templates/templates/external-secrets/externalsecret-keycloak-broker.yaml
  deploy-templates/templates/keycloak/broker-idp.yaml
  deploy-templates/templates/keycloak/keycloakauthflow.yaml
  deploy-templates/templates/keycloak/realm.yaml
  deploy-templates/values.yaml
Labels: enhancement

#225 fix: Update keycloak secret definition
  deploy-templates/templates/external-secrets/externalsecret-keycloak-broker.yaml
Labels: bug

#227 feat: Align keycloakUrl parameter usage
  deploy-templates/templates/keycloak/broker-idp.yaml
Labels: bug

#228 chore: Align oauth2-proxy issuer url
  deploy-templates/templates/oauth2-proxy/configmap.yaml
Labels: enhancement

#229 docs: Update release timeline (#187)
  docs/supported-versions.md
Labels: documentation
