Repository epam/edp-install, pull requests merged in 2024-09, with the labels that each got.

#269 feat: Add the ability to enable tekton-pipelines monitoring (#268)
  deploy-templates/README.md
  deploy-templates/values.yaml
Labels: enhancement

#295 chore: Validate 'type' field for QuickLink resources (#294)
  deploy-templates/templates/quick-links/codemie.yaml
  deploy-templates/templates/quick-links/docker-registry.yaml
  deploy-templates/values.yaml
Labels: enhancement

#290 chore: Remove oauth2proxy resources from chart(#289)
  deploy-templates/README.md
  deploy-templates/templates/_helpers.tpl
  deploy-templates/templates/external-secrets/externalsecret-cookie-oauth2.yaml
  deploy-templates/templates/external-secrets/externalsecret-keycloak-broker.yaml
  deploy-templates/templates/external-secrets/externalsecret-keycloak.yaml
  deploy-templates/templates/keycloak/broker-idp.yaml
  deploy-templates/templates/keycloak/clientscope-edp.yaml
  deploy-templates/templates/keycloak/keycloak.yaml
  deploy-templates/templates/keycloak/keycloakauthflow.yaml
  deploy-templates/templates/keycloak/keycloakclient-oauth2-proxy.yaml
  deploy-templates/templates/keycloak/realm.yaml
  deploy-templates/templates/keycloak/realmrolebatch.yaml
  deploy-templates/templates/oauth2-proxy/configmap.yaml
  deploy-templates/templates/oauth2-proxy/deployment.yaml
  deploy-templates/templates/oauth2-proxy/ingress.yaml
  deploy-templates/templates/oauth2-proxy/route.yaml
  deploy-templates/templates/oauth2-proxy/service.yaml
  deploy-templates/templates/oauth2-proxy/serviceaccount.yaml
  deploy-templates/templates/quick-links/keycloak.yaml
  deploy-templates/values.yaml
Labels: enhancement

#296 fix: Align templates variables(#289)
  deploy-templates/templates/_helpers.tpl
Labels: bug

#299 docs: Update KRCI logo (#298)
  docs/assets/edp-logo-150x150-black.png
  docs/assets/krci-logo-267×150-white.png
Labels: documentation
