Repository epam/edp-install, pull requests merged in 2024-10, with the labels that each got.

#307 feat: Add Support for BitBucket as GitProvider (#306)
  deploy-templates/README.md
  deploy-templates/values.yaml
Labels: feature

#304 chore: Align kubernetes rbac
  deploy-templates/templates/rbac/role_builder.yaml
  deploy-templates/templates/rbac/role_deployer.yaml
  deploy-templates/templates/rbac/role_developer.yaml
  deploy-templates/templates/rbac/role_edp_aggregate_view.yaml
  deploy-templates/templates/rbac/rolebinding_builder.yaml
  deploy-templates/templates/rbac/rolebinding_deployer.yaml
Labels: enhancement

#308 docs: Update changelog file for release notes (#292)
  CHANGELOG.md
Labels: documentation

#310 chore: Move Git Providers data to separate AWS PS object (#309)
  deploy-templates/README.md
  deploy-templates/templates/external-secrets/externalsecret-gitprovider.yaml
  deploy-templates/values.yaml
Labels: enhancement

#314 chore: Enable permissions to configmaps for developers (#313)
  deploy-templates/templates/rbac/role_developer.yaml
Labels: enhancement

#317 chore: Add apiGatewayUrl field to edp-config CM (#316)
  deploy-templates/README.md
  deploy-templates/templates/edp_config_map.yaml
  deploy-templates/values.yaml
Labels: enhancement

#319 chore: Update current development version (#318)
  deploy-templates/Chart.lock
  deploy-templates/Chart.yaml
  deploy-templates/README.md
Labels: enhancement

#320 chore: Update current development version (#318)
  deploy-templates/Chart.lock
  deploy-templates/Chart.yaml
  deploy-templates/README.md
Labels: enhancement

#321 chore: Update current development version (#318)
  CHANGELOG.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
Labels: enhancement

#312 docs: Update RELEASES md file (#311)
  RELEASES.md
Labels: documentation

#323 docs: Update RELEASES md file in 3_10 branch (#311)
  RELEASES.md
Labels: documentation

#324 chore: Update Pull Request Template (#107)
  pull_request_template.md
Labels: enhancement

#326 chore: Update OIDC configuration for edp-headlamp (#325)
  deploy-templates/README.md
  deploy-templates/values-no-ingress.yaml
  deploy-templates/values.yaml
Labels: enhancement

#328 chore: Add ApprovalTask CRD (#318)
  deploy-templates/templates/crds/edp.epam.com_approvaltasks.yaml
Labels: bug
