Repository epam/edp-install, pull requests merged in 2024-06, with the labels that each got.

#215 docs: Add cases to Troubleshooting section (#214)
  docs/assets/operator-guide/codebase_synced.png
  docs/assets/operator-guide/insufficient_permissions.png
  docs/assets/operator-guide/invalid_codebase_name.png
  docs/assets/operator-guide/resource_observability_issue.png
  docs/assets/operator-guide/stage_is_not_synced.png
  docs/assets/operator-guide/stage_is_now_synced.png
  docs/operator-guide/namespace-management.md
  docs/operator-guide/troubleshooting/application-not-built.md
  docs/operator-guide/troubleshooting/invalid-codebase-name.md
  docs/operator-guide/troubleshooting/overview.md
  docs/operator-guide/troubleshooting/resource-observability.md
  docs/operator-guide/troubleshooting/troubleshoot-applications.md
  docs/operator-guide/troubleshooting/troubleshoot-container-registries.md
  docs/operator-guide/troubleshooting/troubleshoot-git-server.md
  docs/operator-guide/troubleshooting/troubleshoot-stages.md
  mkdocs.yml
Labels: documentation

#234 chore: Add assets for the documentation (#214)
  docs/assets/ai/developer-frontend-jane.png
  docs/assets/ai/developer-python-nicolas.png
Labels: CodeMie

#233 chore: Update argocd diff
  deploy-templates/templates/keycloak/broker-idp.yaml
  deploy-templates/templates/openshift/role_openshift.yaml
  deploy-templates/templates/openshift/rolebinding_edp_kaniko_registry_editor.yaml
  deploy-templates/templates/openshift/rolebinding_openshift.yaml
  deploy-templates/templates/openshift/rolebinding_openshift_admin.yaml
Labels: dependencies

#236 docs: Update velero installation guide(#235)
  docs/operator-guide/install-velero.md
Labels: documentation

#238 fix: Add rbac for portal widgets(#237)
  deploy-templates/templates/rbac/role_developer.yaml
Labels: bug

#240 chore: Update release version to 3.9.0
  deploy-templates/Chart.lock
  deploy-templates/Chart.yaml
  deploy-templates/README.md
Labels: enhancement

#241 chore: Update current development version
  CHANGELOG.md
  deploy-templates/Chart.lock
  deploy-templates/Chart.yaml
  deploy-templates/README.md
Labels: enhancement

#243 docs: Update the RELEASES md file (#242)
  RELEASES.md
Labels: documentation

#247 docs: Adjust the RELEASES md file again (#242)
  RELEASES.md
Labels: documentation

#249 docs: Upgrade Documentation for KubeRocketCI 3.9.0
  docs/operator-guide/install-edp.md
  docs/operator-guide/upgrade-edp-3.9.md
  docs/supported-versions.md
  mkdocs.yml
Labels: documentation
