Repository epam/edp-install, pull requests merged in 2024-08, with the labels that each got.

#274 chore: Update KubeRocketCI names and documentation links (#273)
  .github/workflows/release.yaml
  README.md
  build.groovy
  code-review.groovy
  create-release.groovy
  deploy-templates/Chart.yaml
  deploy-templates/README.md
  deploy-templates/values.yaml
  helmfiles/README.md
  helmfiles/envs/ci.yaml
  helmfiles/envs/platform.yaml
  helmfiles/releases/edp-install.yaml
  helmfiles/releases/keycloak.yaml
Labels: routine

#277 chore: Disable Tekton dashboard deployments(#276)
  deploy-templates/README.md
  deploy-templates/values.yaml
Labels: enhancement

#280 docs: Replace EDP with KubeRocketCI in README md (#278)
  README.md
Labels: documentation
